# Generated by Django 5.2.1 on 2025-05-24 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней попытки')),
                ('status', models.CharField(choices=[('failed', 'не успешно'), ('success', 'успешно')], default='success', verbose_name='статус последней попытки')),
                ('response', models.TextField(verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Email должен быть от 5 до 254 символов'), django.core.validators.MaxLengthValidator(254, 'Email должен быть от 5 до 254 символов')], verbose_name='электронная почта')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='отчество')),
                ('comment', models.TextField(max_length=500, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('body', models.TextField(blank=True, max_length=5000, null=True, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время рассылки')),
                ('periodicity', models.CharField(choices=[('month', 'раз в месяц'), ('day', 'раз в день'), ('week', 'раз в неделю')], default='day', verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('completed', 'завершена'), ('launched', 'запущена'), ('created', 'создана')], default='created', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
