# Generated by Django 5.2.1 on 2025-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('failed', 'не успешно')], default='success', verbose_name='статус последней попытки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('week', 'раз в неделю'), ('day', 'раз в день'), ('month', 'раз в месяц')], default='day', verbose_name='периодичность рассылки'),
        ),
    ]
