# Generated by Django 5.2.1 on 2025-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attempt_status_alter_newsletter_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('failed', 'не успешно'), ('success', 'успешно')], default='success', verbose_name='статус последней попытки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('week', 'раз в неделю'), ('month', 'раз в месяц'), ('day', 'раз в день')], default='day', verbose_name='периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('launched', 'запущена'), ('created', 'создана'), ('completed', 'завершена')], default='created', verbose_name='статус'),
        ),
    ]
