# Generated by Django 5.2.1 on 2025-05-24 21:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attempt_status_alter_newsletter_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('failed', 'не успешно')], default='success', verbose_name='статус последней попытки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Email должен быть от 5 до 254 символов'), django.core.validators.MaxLengthValidator(254, 'Email должен быть от 5 до 254 символов')], verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='', max_length=5000, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', verbose_name='периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('completed', 'завершена'), ('launched', 'запущена')], default='created', verbose_name='статус'),
        ),
    ]
