# Generated by Django 5.2.1 on 2025-05-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attempt_date_time_alter_attempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('failed', 'не успешно'), ('success', 'успешно')], default='success', verbose_name='статус последней попытки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('month', 'раз в месяц'), ('day', 'раз в день'), ('week', 'раз в неделю')], default='day', verbose_name='периодичность рассылки'),
        ),
    ]
